---
version: "3.7"
services:
  vault-enterprise:
    image: docker.io/hashicorp/vault-enterprise:1.15.1-ent
    command: vault server -dev-tls
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_LICENSE: ${VAULT_LICENSE}
    ports:
      - 8200:8200
    privileged: true
